### ISSUE TITLE
Bugs

### ISSUE THREAD

**Issue by PartapSBimrah** [amsavarthan/hify#1]
There are many dependencies deprecated that why project gettings a lot of errors. I don't know you are aware of this or not. Make sure and fix all the errors and Android studio has been already updated and many things not working in this Android Studio.

**Comment by amsavarthan** [comment]
I have put on hold the development process for this project. I am aware
that many things have changed will start up this project again if I get
some sponsor.

**Comment by PartapSBimrah** [comment]
I will sponsor and get the rights (copyright) of this project.
